---
kind: pipeline
type: docker
name: Build

platform:
  os: linux
  arch: amd64

steps:
  - name: Install dependencies
    image: node:21-alpine3.17
    commands:
      - yarn

  - name: Lint project
    image: node:21-alpine3.17
    commands:
      - yarn lint

  - name: Build
    image: node:21-alpine3.17
    commands:
      - yarn build

  - name: Publish to ghcr
    image: plugins/docker
    settings:
      registry: ghcr.io
      repo: ghcr.io/kevinmidboe/k9e.no
      dockerfile: Dockerfile
      username:
        from_secret: GITHUB_USERNAME
      password:
        from_secret: GITHUB_PASSWORD
      tags:
        - latest
        - ${DRONE_COMMIT_SHA}
    when:
      event:
        include:
          - push
        exclude:
          - pull_request
      branch:
        - main
        - feat/ingress

---
kind: pipeline
type: docker
name: Deploy

platform:
  os: linux
  arch: amd64

steps:
  - name: Deploy to kubernetes
    image: alpine/k8s:1.25.15
    commands:
      - mkdir -p /root/.kube
      - echo $KUBE_CONFIG | base64 -di > /root/.kube/config
      - export IMAGE=ghcr.io/kevinmidboe/k9e.no:${DRONE_COMMIT_SHA}
      - cat .kubernetes/*.yml
        | envsubst
        | kubectl --kubeconfig=/root/.kube/config apply -f -
    environment:
      KUBE_CONFIG:
        from_secret: KUBE_CONFIG
    when:
      event:
        include:
          - push
        exclude:
          - pull_request
      branch:
        - main
        - feat/ingress

depends_on:
  - Build
---
kind: signature
hmac: 1d062e2faf0fcc8b1e6140c76d54d7305cd0fea7c7f35cc070f05aaaa5cf0f3e

...
